// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDC8SUrOUdaiZRSWn383AnFB_RmHC_bMg',
    appId: '1:799999561337:android:ec0db02a3cb76f4a2f4ea8',
    messagingSenderId: '799999561337',
    projectId: 'itec27001',
    storageBucket: 'itec27001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZ9OadySh0aRLxHp3enFmFZ3qtC_6pZU',
    appId: '1:799999561337:ios:2f3b6b5f488f4f902f4ea8',
    messagingSenderId: '799999561337',
    projectId: 'itec27001',
    storageBucket: 'itec27001.appspot.com',
    iosClientId: '799999561337-g6gac778rd45c5bbom832lnoqkmthj7i.apps.googleusercontent.com',
    iosBundleId: 'com.itec.app',
  );
}
